//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _SEQUENCEPATHCORE_HH
#define _SEQUENCEPATHCORE_HH
	
#include "aceSmartSoft.hh"
#include <iostream>

#include <vector>
#include <atomic>
#include <CommYARP_BT/CommTickResult.hh>
#include <CommYARP_BT/CommTickCommand.hh>

class SequencePathCore
{
private:

public:
	SequencePathCore();


	CommYARP_BT::CommTickCommand cmd;
	int reqId;
	std::mutex mutex;
	std::atomic<bool> isNewData {false};
	std::atomic<bool> isClosing {false};
	std::condition_variable gotNewData;

	int currentStep{0};
    std::vector<std::string> inputData;
};
	
#endif
