//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "BaseStateQueryServiceAnswHandler.hh"
#include "Test_QueryServer.hh"

BaseStateQueryServiceAnswHandler::BaseStateQueryServiceAnswHandler(Smart::IQueryServerPattern<CommBasicObjects::CommVoid, CommBasicObjects::CommBaseState, SmartACE::QueryId>* server)
:	BaseStateQueryServiceAnswHandlerCore(server)
{
	
}

BaseStateQueryServiceAnswHandler::~BaseStateQueryServiceAnswHandler()
{
	
}


void BaseStateQueryServiceAnswHandler::handleQuery(const SmartACE::QueryId &id, const CommBasicObjects::CommVoid& request) 
{
	CommBasicObjects::CommBaseState answer;
	
	// implement your query handling logic here and fill in the answer object
	
	this->server->answer(id, answer);
}
