//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _BASESTATEQUERYSERVICEANSWHANDLER_USER_HH
#define _BASESTATEQUERYSERVICEANSWHANDLER_USER_HH
		
#include "BaseStateQueryServiceAnswHandlerCore.hh"

class BaseStateQueryServiceAnswHandler : public BaseStateQueryServiceAnswHandlerCore
{
protected:
public:
	BaseStateQueryServiceAnswHandler(Smart::IQueryServerPattern<CommBasicObjects::CommVoid, CommBasicObjects::CommBaseState, SmartACE::QueryId>* server);
	virtual ~BaseStateQueryServiceAnswHandler();
	virtual void handleQuery(const SmartACE::QueryId &id, const CommBasicObjects::CommVoid& request);
};
#endif
