//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMYARP_BT_COMMTICKCOMMAND_DATA_H_
#define COMMYARP_BT_COMMTICKCOMMAND_DATA_H_

#include "CommYARP_BT/enumTickCommandData.hh"

#include <string>

namespace CommYARP_BTIDL 
{
	struct CommTickCommand
	{
		CommYARP_BTIDL::TickCommand command;
		std::string parameter;
  	};
};

#endif /* COMMYARP_BT_COMMTICKCOMMAND_DATA_H_ */
