//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommYARP_BT/CommTickCommandCore.hh"

// serialization/deserialization operators
//#include "CommYARP_BT/CommTickCommandACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace CommYARP_BT 
{
	const char* CommTickCommandCore::getCompiledHash()
	{
		return CommYARP_BTIDL::REPO_HASH;
	}
	
	void CommTickCommandCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
	}
	
	void CommTickCommandCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "CommTickCommandCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
	}
	
	#ifdef ENABLE_HASH
	size_t CommTickCommandCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		boost::hash_combine(seed, data.command);
		boost::hash_combine(seed, std::string(data.parameter.c_str()));
		
		return seed;
	}
	#endif
	
	// default constructor
	CommTickCommandCore::CommTickCommandCore()
	:	idl_CommTickCommand()
	{  
		setCommand(CommYARP_BT::TickCommand());
		setParameter("");
	}
	
	CommTickCommandCore::CommTickCommandCore(const DATATYPE &data)
	:	idl_CommTickCommand(data)
	{  }

	CommTickCommandCore::~CommTickCommandCore()
	{  }
	
	void CommTickCommandCore::to_ostream(std::ostream &os) const
	{
	  os << "CommTickCommand(";
	  getCommand().to_ostream(os);
	  os << getParameter() << " ";
	  os << ") ";
	}
	
	// convert to xml stream
	void CommTickCommandCore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<command>";
		getCommand().to_xml(os, indent);
		os << indent << "</command>";
		os << indent << "<parameter>" << getParameter() << "</parameter>";
	}
	
	// restore from xml stream
	void CommTickCommandCore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_command("<command>");
		static const Smart::KnuthMorrisPratt kmp_parameter("<parameter>");
		
		if(kmp_command.search(is)) {
			CommYARP_BT::TickCommand commandItem;
			commandItem.from_xml(is);
			setCommand(commandItem);
		}
		if(kmp_parameter.search(is)) {
			std::string parameterItem;
			is >> parameterItem;
			setParameter(parameterItem);
		}
	}
	
	/*
	void CommTickCommandCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		CommYARP_BTIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(CommYARP_BTIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see CommTickCommandACE.hh)
		cdr << idl_CommTickCommand;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_CommTickCommand);
		cdr << data_hash;
		// std::cout << "CommTickCommandCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void CommTickCommandCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		CommYARP_BTIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see CommTickCommandACE.hh)
		cdr >> idl_CommTickCommand;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_CommTickCommand);
		assert(data_hash == own_hash);
		// std::cout << "CommTickCommandCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace CommYARP_BT */
