//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMYARP_BT_COMMTICKRESULT_ACE_H_
#define COMMYARP_BT_COMMTICKRESULT_ACE_H_

#include "CommYARP_BT/CommTickResult.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure CommTickResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommYARP_BTIDL::CommTickResult &data);

// de-serialization operator for DataStructure CommTickResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommYARP_BTIDL::CommTickResult &data);

// serialization operator for CommunicationObject CommTickResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommYARP_BT::CommTickResult &obj);

// de-serialization operator for CommunicationObject CommTickResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommYARP_BT::CommTickResult &obj);

#endif /* COMMYARP_BT_COMMTICKRESULT_ACE_H_ */
