//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommYARP_BT/CommTickCommandACE.hh"
#include <ace/SString.h>
#include "CommYARP_BT/enumTickCommandData.hh"

// serialization operator for element CommTickCommand
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommYARP_BTIDL::CommTickCommand &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element command
	good_bit = good_bit && cdr.write_long(data.command);
	// serialize list-element parameter
	good_bit = good_bit && cdr << ACE_CString(data.parameter.c_str());
	
	return good_bit;
}

// de-serialization operator for element CommTickCommand
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommYARP_BTIDL::CommTickCommand &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element command
	good_bit = good_bit && cdr.read_long(data.command);
	// deserialize string-type element parameter
	ACE_CString data_parameter_str;
	good_bit = good_bit && cdr >> data_parameter_str;
	data.parameter = data_parameter_str.c_str();
	
	return good_bit;
}

// serialization operator for CommunicationObject CommTickCommand
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommYARP_BT::CommTickCommand &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommTickCommand
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommYARP_BT::CommTickCommand &obj)
{
	return cdr >> obj.set();
}
