//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMYARP_BT_COMMTICKCOMMAND_CORE_H_
#define COMMYARP_BT_COMMTICKCOMMAND_CORE_H_

#include "CommYARP_BT/CommTickCommandData.hh"
#include "CommYARP_BT/enumTickCommand.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommYARP_BT {
	
class CommTickCommandCore {
protected:
	// data structure
	CommYARP_BTIDL::CommTickCommand idl_CommTickCommand;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommYARP_BTIDL::CommTickCommand DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommTickCommandCore();
	CommTickCommandCore(const DATATYPE &data);
	// default destructor
	virtual ~CommTickCommandCore();
	
	const DATATYPE& get() const { return idl_CommTickCommand; }
	operator const DATATYPE&() const { return idl_CommTickCommand; }
	DATATYPE& set() { return idl_CommTickCommand; }

	static inline std::string identifier(void) { return "CommYARP_BT::CommTickCommand"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Command
	inline CommYARP_BT::TickCommand getCommand() const { return CommYARP_BT::TickCommand(idl_CommTickCommand.command); }
	inline CommTickCommandCore& setCommand(const CommYARP_BT::TickCommand &command) { idl_CommTickCommand.command = command; return *this; }
	
	// getter and setter for element Parameter
	inline std::string getParameter() const { return idl_CommTickCommand.parameter; }
	inline CommTickCommandCore& setParameter(const std::string &parameter) { idl_CommTickCommand.parameter = parameter; return *this; }
};

} /* namespace CommYARP_BT */
#endif /* COMMYARP_BT_COMMTICKCOMMAND_CORE_H_ */
