//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMYARP_BT_TICKCOMMAND_ENUM_H_
#define COMMYARP_BT_TICKCOMMAND_ENUM_H_

#include <CommYARP_BT/enumTickCommandData.hh>

#include <string>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace CommYARP_BT {
	
	class TickCommand {
	private:
		CommYARP_BTIDL::TickCommand value;
		
	public:
		enum ENUM_TickCommand {
			ENUM_VALUE_UNDEFINED = 0,
			Tick = 1,
			Halt = 2
		};
		
		// default constructor
		TickCommand() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		TickCommand(ENUM_TickCommand e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type
		TickCommand(CommYARP_BTIDL::TickCommand e) {
			value = e;
		}
		
		//const CommYARP_BTIDL::TickCommand& get() const { return value; }
		
		// ENUM operator
		operator ENUM_TickCommand() const {
			return static_cast<ENUM_TickCommand>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_TickCommand t) const {
			return this->value == t;
		}
		
		std::string to_string() const {
			std::string result = "";
			switch (value) {
				case Tick:
					result = "TickCommand::Tick";
					break;
				case Halt:
					result = "TickCommand::Halt";
					break;
				default:
					result = "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const TickCommand &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
