//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMYARP_BT_TICKRESULT_ENUM_H_
#define COMMYARP_BT_TICKRESULT_ENUM_H_

#include <CommYARP_BT/enumTickResultData.hh>

#include <string>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace CommYARP_BT {
	
	class TickResult {
	private:
		CommYARP_BTIDL::TickResult value;
		
	public:
		enum ENUM_TickResult {
			ENUM_VALUE_UNDEFINED = 0,
			Running = 1,
			Success = 2,
			Failure = 3,
			Idle = 4,
			Halted = 5,
			Error = 6
		};
		
		// default constructor
		TickResult() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		TickResult(ENUM_TickResult e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type
		TickResult(CommYARP_BTIDL::TickResult e) {
			value = e;
		}
		
		//const CommYARP_BTIDL::TickResult& get() const { return value; }
		
		// ENUM operator
		operator ENUM_TickResult() const {
			return static_cast<ENUM_TickResult>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_TickResult t) const {
			return this->value == t;
		}
		
		std::string to_string() const {
			std::string result = "";
			switch (value) {
				case Running:
					result = "TickResult::Running";
					break;
				case Success:
					result = "TickResult::Success";
					break;
				case Failure:
					result = "TickResult::Failure";
					break;
				case Idle:
					result = "TickResult::Idle";
					break;
				case Halted:
					result = "TickResult::Halted";
					break;
				case Error:
					result = "TickResult::Error";
					break;
				default:
					result = "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const TickResult &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
