//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _BT_RUNNERCORE_HH
#define _BT_RUNNERCORE_HH
	
#include "aceSmartSoft.hh"
#include <iostream>

#include <behaviortree_cpp/bt_factory.h>
#include <behaviortree_cpp/xml_parsing.h>

class BT_runnerCore
{
private:

public:
	BT::Tree  tree_cpp;
    BT::BehaviorTreeFactory factory;
    std::map<std::string, BT::TreeNode::Ptr> nodeMap;

	BT_runnerCore();
};
	
#endif
