//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _TASK1_HH
#define _TASK1_HH

#include "Task1Core.hh"
#include <caml/mlvalues.h>

class Task1  : public Task1Core
{
private:
	value behaviourTree;

public:
	Task1(SmartACE::SmartComponent *comp);
	virtual ~Task1();
	
	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
