//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _TEST_DUMMYSENDPATTERN_CLIENT_HH
#define _TEST_DUMMYSENDPATTERN_CLIENT_HH
	
#include <iostream>
#include "aceSmartSoft.hh"
#include "smartQueryServerTaskTrigger_T.h"
#include "Test_DummySendPattern_ClientCore.hh"
#include "Test_DummySendPattern_ClientImpl.hh"

// include communication objects
#include <CommBasicObjects/CommBaseState.hh>
#include <CommBasicObjects/CommBaseStateACE.hh>

// include tasks
#include "Task.hh"
// include UpcallManagers

// include input-handler
// include input-handler


// include handler
#include "CompHandler.hh"


#include "SmartStateChangeHandler.hh"

#define COMP Test_DummySendPattern_Client::instance()

class Test_DummySendPattern_Client : public Test_DummySendPattern_ClientCore {
private:
	static Test_DummySendPattern_Client _test_DummySendPattern_Client;
	
	// constructor
	Test_DummySendPattern_Client();
	
	// copy-constructor
	Test_DummySendPattern_Client(const Test_DummySendPattern_Client& cc);
	
	// destructor
	~Test_DummySendPattern_Client() { };
	
	// load parameter from ini file
	void loadParameter(int argc, char* argv[]);
	
	// instantiate comp-handler
	CompHandler compHandler;
	
	Smart::TaskTriggerSubject* getInputTaskTriggerFromString(const std::string &client);
	
public:
	// component
	Test_DummySendPattern_ClientImpl *component;
	
	
	// define tasks
	Smart::TaskTriggerSubject* taskTrigger;
	Task *task;
	
	// define input-ports
	
	// define request-ports
	
	// define input-handler
	
	// define output-ports
	Smart::IPushServerPattern<CommBasicObjects::CommBaseState> *baseStateServiceOut;
	
	// define answer-ports
	
	// define request-handlers
	
	
	// define default slave ports
	SmartACE::StateSlave *stateSlave;
	SmartStateChangeHandler *stateChangeHandler;
	SmartACE::WiringSlave *wiringSlave;
	
	
	void init(int argc, char *argv[]);
	void run();
	
	void setStartupFinished();
	Smart::StatusCode connectAndStartAllServices();
	void startAllTasks();
	void startAllTimers();
	

	// return singleton instance
	static Test_DummySendPattern_Client* instance()
	{
		return (Test_DummySendPattern_Client*)&_test_DummySendPattern_Client;
	}
	
	// connections parameter
	struct connections_struct
	{
		// component struct
		struct component_struct
		{
			// the name of the component
			std::string name;
			std::string initialMainState;
			std::string defaultScheduler;
			bool useLogger;
		} component;
		
		//--- task parameter ---
		struct Task_struct {
			double minActFreq;
			double maxActFreq;
			std::string trigger;
			// only one of the following two params is 
			// actually used at run-time according 
			// to the system config model
			double periodicActFreq;
			// or
			std::string inPortRef;
			int prescale;
			// scheduling parameters
			std::string scheduler;
			int priority;
			int cpuAffinity;
		} task;
		
		//--- upcall parameter ---
		
		//--- server port parameter ---
		struct BaseStateServiceOut_struct {
				std::string serviceName;
		} baseStateServiceOut;
	
		//--- client port parameter ---
		
	} connections;
};
#endif
