//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _BT_TICK_QUERY_HANDLER_USER_HH
#define _BT_TICK_QUERY_HANDLER_USER_HH
		
#include "BT_Tick_Query_HandlerCore.hh"

class BT_Tick_Query_Handler : public BT_Tick_Query_HandlerCore
{
protected:
public:
	BT_Tick_Query_Handler(Smart::IQueryServerPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult, SmartACE::QueryId>* server);
	virtual ~BT_Tick_Query_Handler();
	virtual void handleQuery(const SmartACE::QueryId &id, const CommYARP_BT::CommTickCommand& request);
};
#endif
