//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "BT_Tick_Query_Handler.hh"
#include "BT_tickDispatcher.hh"

BT_Tick_Query_Handler::BT_Tick_Query_Handler(Smart::IQueryServerPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult, SmartACE::QueryId>* server)
:	BT_Tick_Query_HandlerCore(server)
{
	
}

BT_Tick_Query_Handler::~BT_Tick_Query_Handler()
{
	
}


void BT_Tick_Query_Handler::handleQuery(const SmartACE::QueryId &id, const CommYARP_BT::CommTickCommand& request) 
{
	CommYARP_BT::CommTickResult answer;
	
	// implement your query handling logic here and fill in the answer object
	
	CommYARP_BT::TickCommand cmd = request.getCommand();
	CommYARP_BT::TickResult  res = CommYARP_BT::TickResult::Error;
	std::string tickParam = request.getParameter();

	std::cout << "\n\n-----\nTick Manager Received tick request [id " << id << "] " << tickParam << std::endl;

	//	sleep(4);

	COMP->reqId = id;
	COMP->cmd = request;
	COMP->isNewData = true;
	COMP->gotNewData.notify_all();

//	std::string skill = tickParam;
//	auto it = COMP->tickables_map.find(skill);
//	if( it == COMP->tickables_map.end())
//	{
//		std::cout << "Error: skill " << skill << " not found!";
//		res = CommYARP_BT::TickResult::Error;
//	}
//	else
//	{
//		res = (int) (*it).second.tickerInstance->tick(cmd /* (*it).second.command*/, (*it).second.params);
//	}
//
//	answer.setResult(res);
//	std::cout << "answering query id " << id << "  with value: " << answer.getResult().to_string() << "  (res " << (int)res << " " << res << ")" << std::endl << std::endl;
//	this->server->answer(id, answer);
}
