//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _BT_TICK_HANDLER_CORE_HH
#define _BT_TICK_HANDLER_CORE_HH
		
#include "aceSmartSoft.hh"

#include <CommYARP_BT/CommTickCommand.hh>
#include <CommYARP_BT/CommTickResult.hh>

// include the input interfaces (if any)

// include all interaction-observer interfaces
#include <BT_tick_HandlerObserverInterface.hh>

class BT_tick_HandlerCore 
:	public Smart::IQueryServerHandler<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult, SmartACE::QueryId>
,	public Smart::TaskTriggerSubject
{
private:

	virtual void updateAllCommObjects();

/**
 * Implementation of the Subject part of an InteractionObserver
 */
private:
	std::mutex interaction_observers_mutex;
	std::list<BT_tick_HandlerObserverInterface*> interaction_observers;
protected:
	void notify_all_interaction_observers();
public:
	void attach_interaction_observer(BT_tick_HandlerObserverInterface *observer);
	void detach_interaction_observer(BT_tick_HandlerObserverInterface *observer);

protected:
	
public:
	BT_tick_HandlerCore(Smart::IQueryServerPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult, SmartACE::QueryId>* server);
	virtual ~BT_tick_HandlerCore();
	//virtual void handleQuery(const SmartACE::QueryId &id, const CommYARP_BT::CommTickCommand& request);
};
#endif
