//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _BT_TICKDISPATCHER_HH
#define _BT_TICKDISPATCHER_HH
	
#include <iostream>
#include "aceSmartSoft.hh"
#include "smartQueryServerTaskTrigger_T.h"
#include "BT_tickDispatcherCore.hh"
#include "BT_tickDispatcherImpl.hh"

// include communication objects
#include <CommYARP_BT/CommTickCommand.hh>
#include <CommYARP_BT/CommTickCommandACE.hh>
#include <CommYARP_BT/CommTickResult.hh>
#include <CommYARP_BT/CommTickResultACE.hh>

// include tasks
#include "Activity.hh"
// include UpcallManagers

// include input-handler
// include input-handler
#include "BT_Tick_Query_Handler.hh"


// include handler
#include "CompHandler.hh"

#include "ParameterStateStruct.hh"
#include "ParameterUpdateHandler.hh"

#include "SmartStateChangeHandler.hh"

#define COMP BT_tickDispatcher::instance()

class BT_tickDispatcher : public BT_tickDispatcherCore {
private:
	static BT_tickDispatcher _bT_tickDispatcher;
	
	// constructor
	BT_tickDispatcher();
	
	// copy-constructor
	BT_tickDispatcher(const BT_tickDispatcher& cc);
	
	// destructor
	~BT_tickDispatcher() { };
	
	// load parameter from ini file
	void loadParameter(int argc, char* argv[]);
	
	// instantiate comp-handler
	CompHandler compHandler;
	
	Smart::TaskTriggerSubject* getInputTaskTriggerFromString(const std::string &client);
	
public:
	// component
	BT_tickDispatcherImpl *component;
	
	ParameterStateStruct getGlobalState() const
	{
		return paramHandler.getGlobalState();
	}
	
	// define tasks
	Smart::TaskTriggerSubject* activityTrigger;
	Activity *activity;
	
	// define input-ports
	
	// define request-ports
	Smart::IQueryClientPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult,SmartACE::QueryId> *bT_Navig_tick;
	Smart::IQueryClientPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult,SmartACE::QueryId> *bT_manip_tick;
	Smart::IQueryClientPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult,SmartACE::QueryId> *bT_vision_tick;
	
	// define input-handler
	
	// define output-ports
	
	// define answer-ports
	Smart::IQueryServerPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult,SmartACE::QueryId> *bT_Tick_input;
	Smart::QueryServerTaskTrigger<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult,SmartACE::QueryId> *bT_Tick_inputInputTaskTrigger;
	
	// define request-handlers
	BT_Tick_Query_Handler *bT_Tick_Query_Handler;
	
	
	// define default slave ports
	SmartACE::StateSlave *stateSlave;
	SmartStateChangeHandler *stateChangeHandler;
	SmartACE::WiringSlave *wiringSlave;
	ParamUpdateHandler paramHandler;
	SmartACE::ParameterSlave *param;
	
	
	void init(int argc, char *argv[]);
	void run();
	
	void setStartupFinished();
	Smart::StatusCode connectAndStartAllServices();
	void startAllTasks();
	void startAllTimers();
	
	Smart::StatusCode connectBT_Navig_tick(const std::string &serverName, const std::string &serviceName);
	Smart::StatusCode connectBT_manip_tick(const std::string &serverName, const std::string &serviceName);
	Smart::StatusCode connectBT_vision_tick(const std::string &serverName, const std::string &serviceName);

	// return singleton instance
	static BT_tickDispatcher* instance()
	{
		return (BT_tickDispatcher*)&_bT_tickDispatcher;
	}
	
	// connections parameter
	struct connections_struct
	{
		// component struct
		struct component_struct
		{
			// the name of the component
			std::string name;
			std::string initialComponentMode;
			std::string defaultScheduler;
			bool useLogger;
		} component;
		
		//--- task parameter ---
		struct Activity_struct {
			double minActFreq;
			double maxActFreq;
			std::string trigger;
			// only one of the following two params is 
			// actually used at run-time according 
			// to the system config model
			double periodicActFreq;
			// or
			std::string inPortRef;
			int prescale;
			// scheduling parameters
			std::string scheduler;
			int priority;
			int cpuAffinity;
		} activity;
		
		//--- upcall parameter ---
		
		//--- server port parameter ---
		struct BT_Tick_input_struct {
				std::string serviceName;
		} bT_Tick_input;
	
		//--- client port parameter ---
		struct BT_Navig_tick_struct {
			bool initialConnect;
			std::string serverName;
			std::string serviceName;
			std::string wiringName;
			long interval;
		} bT_Navig_tick;
		struct BT_manip_tick_struct {
			bool initialConnect;
			std::string serverName;
			std::string serviceName;
			std::string wiringName;
			long interval;
		} bT_manip_tick;
		struct BT_vision_tick_struct {
			bool initialConnect;
			std::string serverName;
			std::string serviceName;
			std::string wiringName;
			long interval;
		} bT_vision_tick;
		
	} connections;
};
#endif
