//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _COMPONENT_2_HH
#define _COMPONENT_2_HH
	
#include <iostream>
#include "aceSmartSoft.hh"
#include "smartQueryServerTaskTrigger_T.h"
#include "Component_2Core.hh"
#include "Component_2Impl.hh"

// include communication objects
#include <CommYARP_BT/CommTickCommand.hh>
#include <CommYARP_BT/CommTickCommandACE.hh>
#include <CommYARP_BT/CommTickResult.hh>
#include <CommYARP_BT/CommTickResultACE.hh>

// include tasks
#include "Activity.hh"
// include UpcallManagers

// include input-handler
// include input-handler
#include "MsgHandler.hh"


// include handler
#include "CompHandler.hh"


#include "SmartStateChangeHandler.hh"

#define COMP Component_2::instance()

class Component_2 : public Component_2Core {
private:
	static Component_2 _component_2;
	
	// constructor
	Component_2();
	
	// copy-constructor
	Component_2(const Component_2& cc);
	
	// destructor
	~Component_2() { };
	
	// load parameter from ini file
	void loadParameter(int argc, char* argv[]);
	
	// instantiate comp-handler
	CompHandler compHandler;
	
	Smart::TaskTriggerSubject* getInputTaskTriggerFromString(const std::string &client);
	
public:
	// component
	Component_2Impl *component;
	
	
	// define tasks
	Smart::TaskTriggerSubject* activityTrigger;
	Activity *activity;
	
	// define input-ports
	
	// define request-ports
	Smart::IQueryClientPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult,SmartACE::QueryId> *msgClient;
	
	// define input-handler
	
	// define output-ports
	
	// define answer-ports
	Smart::IQueryServerPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult,SmartACE::QueryId> *msgServer;
	Smart::QueryServerTaskTrigger<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult,SmartACE::QueryId> *msgServerInputTaskTrigger;
	
	// define request-handlers
	MsgHandler *msgHandler;
	
	
	// define default slave ports
	SmartACE::StateSlave *stateSlave;
	SmartStateChangeHandler *stateChangeHandler;
	SmartACE::WiringSlave *wiringSlave;
	
	
	void init(int argc, char *argv[]);
	void run();
	
	void setStartupFinished();
	Smart::StatusCode connectAndStartAllServices();
	void startAllTasks();
	void startAllTimers();
	
	Smart::StatusCode connectMsgClient(const std::string &serverName, const std::string &serviceName);

	// return singleton instance
	static Component_2* instance()
	{
		return (Component_2*)&_component_2;
	}
	
	// connections parameter
	struct connections_struct
	{
		// component struct
		struct component_struct
		{
			// the name of the component
			std::string name;
			std::string initialComponentMode;
			std::string defaultScheduler;
			bool useLogger;
		} component;
		
		//--- task parameter ---
		struct Activity_struct {
			double minActFreq;
			double maxActFreq;
			std::string trigger;
			// only one of the following two params is 
			// actually used at run-time according 
			// to the system config model
			double periodicActFreq;
			// or
			std::string inPortRef;
			int prescale;
			// scheduling parameters
			std::string scheduler;
			int priority;
			int cpuAffinity;
		} activity;
		
		//--- upcall parameter ---
		
		//--- server port parameter ---
		struct MsgServer_struct {
				std::string serviceName;
		} msgServer;
	
		//--- client port parameter ---
		struct MsgClient_struct {
			bool initialConnect;
			std::string serverName;
			std::string serviceName;
			std::string wiringName;
			long interval;
		} msgClient;
		
	} connections;
};
#endif
