//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _COMPONENT_2CORE_HH
#define _COMPONENT_2CORE_HH
	
#include "aceSmartSoft.hh"
#include <iostream>
#include <mutex>
#include <atomic>
#include <condition_variable>

#include <CommYARP_BT/CommTickCommand.hh>
#include <CommYARP_BT/CommTickResult.hh>

class Component_2Core
{
private:

public:
	Component_2Core();

	CommYARP_BT::CommTickCommand cmd;
	int reqId;
	std::mutex mutex;
	std::atomic<bool> isNewData {false};
	std::atomic<bool> isClosing {false};
	std::condition_variable gotNewData;

	static bool getIsNewData(Component_2Core* c) { return c->isNewData;};

};
	
#endif
