#!/bin/bash
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# This script collects the generated ini-file parts and combines them into single ini-files (one for each component artefact)
#

# create ini-file BT_runner.ini
echo "create ini-file BT_runner.ini"
cp src-gen/system/BT_runner.ini src-gen/deployment/
cat src-gen/params/BT_runner.ini >> src-gen/deployment/BT_runner.ini

# create ini-file BT_tickDispatcher.ini
echo "create ini-file BT_tickDispatcher.ini"
cp src-gen/system/BT_tickDispatcher.ini src-gen/deployment/
cat src-gen/params/BT_tickDispatcher.ini >> src-gen/deployment/BT_tickDispatcher.ini

# create ini-file GraspingSkill.ini
echo "create ini-file GraspingSkill.ini"
cp src-gen/system/GraspingSkill.ini src-gen/deployment/
cat src-gen/params/GraspingSkill.ini >> src-gen/deployment/GraspingSkill.ini

# create ini-file Navigationskill.ini
echo "create ini-file Navigationskill.ini"
cp src-gen/system/Navigationskill.ini src-gen/deployment/
cat src-gen/params/Navigationskill.ini >> src-gen/deployment/Navigationskill.ini

# create ini-file VisionSkill.ini
echo "create ini-file VisionSkill.ini"
cp src-gen/system/VisionSkill.ini src-gen/deployment/
cat src-gen/params/VisionSkill.ini >> src-gen/deployment/VisionSkill.ini

