#!/bin/bash
#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# Please do not modify this file. It will be re-generated
# running the code generator.
#--------------------------------------------------------------------------
#
# run this script from the component's root folder to deploy the scenario to device.
#

TARGET_SSHUSER=icub
TARGET_IP=127.0.0.1
TARGET_DIRECTORY="/home/icub/SOFTWARE/deployment_3.6/"
DEPLOYMENT_DIRECTORY=System_Scenario1.deployment/

echo "#######################################################"
echo "## Deployment of Device localhost / $TARGET_IP"
echo "#######################################################"
echo "Target SSH user:      $TARGET_SSHUSER"
echo "Target IP:            $TARGET_IP"
echo "Target directory:     $TARGET_DIRECTORY"
echo "Deployment directory: $DEPLOYMENT_DIRECTORY"

echo "Working directory of deployment script: "`pwd`

echo Sourcing referenced projects
source src-gen/deployment/referenced-projects

DEPLOY_LIBRARIES_USER=""
echo "Sourcing pre-deployment script for BT_runner... (errors might be ignored)"
DEPLOY_LIBRARIES=""
DEPLOY_COMPONENT_FILES=""
source src/predeploy-BT_runner.sh 2>&1

for I in $DEPLOY_LIBRARIES; do
	if [ -e "$SMART_ROOT_ACE/bin/$I" ]; then
		FILE="$SMART_ROOT_ACE/bin/$I"
	else
		FILE="$SMART_ROOT_ACE/lib/$I"
	fi
	DEPLOY_LIBRARIES_USER="$DEPLOY_LIBRARIES_USER $FILE"
done

DEPLOY_COMPONENT_FILES_PATHS_BT_runner=""
for I in $DEPLOY_COMPONENT_FILES; do
	if ls $REFERENCED_PROJECT_BT_runner/$I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_BT_runner="$DEPLOY_COMPONENT_FILES_PATHS_BT_runner $REFERENCED_PROJECT_BT_runner/$I"
	elif ls $I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_BT_runner="$DEPLOY_COMPONENT_FILES_PATHS_BT_runner $I"
	fi
done

echo
echo "Sourcing pre-deployment script for BT_tickDispatcher... (errors might be ignored)"
DEPLOY_LIBRARIES=""
DEPLOY_COMPONENT_FILES=""
source src/predeploy-BT_tickDispatcher.sh 2>&1

for I in $DEPLOY_LIBRARIES; do
	if [ -e "$SMART_ROOT_ACE/bin/$I" ]; then
		FILE="$SMART_ROOT_ACE/bin/$I"
	else
		FILE="$SMART_ROOT_ACE/lib/$I"
	fi
	DEPLOY_LIBRARIES_USER="$DEPLOY_LIBRARIES_USER $FILE"
done

DEPLOY_COMPONENT_FILES_PATHS_BT_tickDispatcher=""
for I in $DEPLOY_COMPONENT_FILES; do
	if ls $REFERENCED_PROJECT_BT_tickDispatcher/$I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_BT_tickDispatcher="$DEPLOY_COMPONENT_FILES_PATHS_BT_tickDispatcher $REFERENCED_PROJECT_BT_tickDispatcher/$I"
	elif ls $I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_BT_tickDispatcher="$DEPLOY_COMPONENT_FILES_PATHS_BT_tickDispatcher $I"
	fi
done

echo
echo "Sourcing pre-deployment script for GraspingSkill... (errors might be ignored)"
DEPLOY_LIBRARIES=""
DEPLOY_COMPONENT_FILES=""
source src/predeploy-GraspingSkill.sh 2>&1

for I in $DEPLOY_LIBRARIES; do
	if [ -e "$SMART_ROOT_ACE/bin/$I" ]; then
		FILE="$SMART_ROOT_ACE/bin/$I"
	else
		FILE="$SMART_ROOT_ACE/lib/$I"
	fi
	DEPLOY_LIBRARIES_USER="$DEPLOY_LIBRARIES_USER $FILE"
done

DEPLOY_COMPONENT_FILES_PATHS_GraspingSkill=""
for I in $DEPLOY_COMPONENT_FILES; do
	if ls $REFERENCED_PROJECT_GraspingSkill/$I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_GraspingSkill="$DEPLOY_COMPONENT_FILES_PATHS_GraspingSkill $REFERENCED_PROJECT_GraspingSkill/$I"
	elif ls $I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_GraspingSkill="$DEPLOY_COMPONENT_FILES_PATHS_GraspingSkill $I"
	fi
done

echo
echo "Sourcing pre-deployment script for Navigationskill... (errors might be ignored)"
DEPLOY_LIBRARIES=""
DEPLOY_COMPONENT_FILES=""
source src/predeploy-Navigationskill.sh 2>&1

for I in $DEPLOY_LIBRARIES; do
	if [ -e "$SMART_ROOT_ACE/bin/$I" ]; then
		FILE="$SMART_ROOT_ACE/bin/$I"
	else
		FILE="$SMART_ROOT_ACE/lib/$I"
	fi
	DEPLOY_LIBRARIES_USER="$DEPLOY_LIBRARIES_USER $FILE"
done

DEPLOY_COMPONENT_FILES_PATHS_YarpNavigationClient=""
for I in $DEPLOY_COMPONENT_FILES; do
	if ls $REFERENCED_PROJECT_YarpNavigationClient/$I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_YarpNavigationClient="$DEPLOY_COMPONENT_FILES_PATHS_YarpNavigationClient $REFERENCED_PROJECT_YarpNavigationClient/$I"
	elif ls $I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_YarpNavigationClient="$DEPLOY_COMPONENT_FILES_PATHS_YarpNavigationClient $I"
	fi
done

echo
echo "Sourcing pre-deployment script for VisionSkill... (errors might be ignored)"
DEPLOY_LIBRARIES=""
DEPLOY_COMPONENT_FILES=""
source src/predeploy-VisionSkill.sh 2>&1

for I in $DEPLOY_LIBRARIES; do
	if [ -e "$SMART_ROOT_ACE/bin/$I" ]; then
		FILE="$SMART_ROOT_ACE/bin/$I"
	else
		FILE="$SMART_ROOT_ACE/lib/$I"
	fi
	DEPLOY_LIBRARIES_USER="$DEPLOY_LIBRARIES_USER $FILE"
done

DEPLOY_COMPONENT_FILES_PATHS_VisionSkill=""
for I in $DEPLOY_COMPONENT_FILES; do
	if ls $REFERENCED_PROJECT_VisionSkill/$I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_VisionSkill="$DEPLOY_COMPONENT_FILES_PATHS_VisionSkill $REFERENCED_PROJECT_VisionSkill/$I"
	elif ls $I > /dev/null 2>&1; then
		DEPLOY_COMPONENT_FILES_PATHS_VisionSkill="$DEPLOY_COMPONENT_FILES_PATHS_VisionSkill $I"
	fi
done

echo


DEPL_FILES="
$SMART_ROOT_ACE/lib/libAceSmartSoftKernel.so
$SMART_ROOT_ACE/lib/libSmartProperty.so.*
src-gen/deployment/tiler.sh
src-gen/deployment/start-localhost.sh
$SMART_ROOT_ACE/bin/NamingService
src-gen/deployment/ns_config.ini
src/BT_runner_data
src/startstop-hooks-BT_runner.sh
$SMART_ROOT_ACE/bin/BT_runner
src-gen/deployment/BT_runner.ini
$SMART_ROOT_ACE/lib/libCommYARP_BT.so*
src/BT_tickDispatcher_data
src/startstop-hooks-BT_tickDispatcher.sh
$SMART_ROOT_ACE/bin/BT_tickDispatcher
src-gen/deployment/BT_tickDispatcher.ini
$SMART_ROOT_ACE/lib/libCommYARP_BT.so*
src/GraspingSkill_data
src/startstop-hooks-GraspingSkill.sh
$SMART_ROOT_ACE/bin/GraspingSkill
src-gen/deployment/GraspingSkill.ini
$SMART_ROOT_ACE/lib/libCommYARP_BT.so*
src/Navigationskill_data
src/startstop-hooks-Navigationskill.sh
$SMART_ROOT_ACE/bin/YarpNavigationClient
src-gen/deployment/Navigationskill.ini
$SMART_ROOT_ACE/lib/libCommYARP_BT.so*
src/VisionSkill_data
src/startstop-hooks-VisionSkill.sh
$SMART_ROOT_ACE/bin/VisionSkill
src-gen/deployment/VisionSkill.ini
$SMART_ROOT_ACE/lib/libCommYARP_BT.so*

$DEPLOY_LIBRARIES_USER
"

FILES_MISSING=false
for FILE in $DEPL_FILES; do
	if [ ! -e $FILE ]; then
		echo "Deployment: No such file or directory: $FILE"
		FILES_MISSING=true
	fi
done

if [ "$FILES_MISSING" = "true" ]; then
	echo
	echo "ERROR: FILES ARE MISSING FROM THE DEPLOYMENT (see above). Did you compile all components?"
	echo 
	exit 1
fi


if [ "$1" = "local" ]; then
	# local deployment
	mkdir -p $DEPLOYMENT_DIRECTORY
	rsync -l -r -v --progress --exclude ".svn" $DEPL_FILES $DEPLOYMENT_DIRECTORY/localhost
else
	# remote deployment
	SSH_TARGET=icub@127.0.0.1:$TARGET_DIRECTORY/$DEPLOYMENT_DIRECTORY
	echo "Deployment to $SSH_TARGET"
	ssh icub@127.0.0.1 mkdir -p $TARGET_DIRECTORY/$DEPLOYMENT_DIRECTORY
	
	TMPDIR=$(mktemp -d --suffix=.deployment) || exit 1
	echo "Temporary directory: $TMPDIR"
	trap "rm -rf $TMPDIR" EXIT
	
	# collect files in $TMPDIR
	#rsync -l -r -v --progress --exclude ".svn" $DEPL_FILES $TMPDIR/
	cp -rv $DEPL_FILES $TMPDIR 2>&1
#rsync -l -r -v --progress --exclude ".svn" $DEPLOY_COMPONENT_FILES_PATHS_BT_runner $TMPDIR/BT_runner_data/
if [ ! "$DEPLOY_COMPONENT_FILES_PATHS_BT_runner" = "" ]; then
	cp -rv $DEPLOY_COMPONENT_FILES_PATHS_BT_runner $TMPDIR/BT_runner_data/ 2>&1
fi

cp -v $REFERENCED_PROJECT_BT_runner/smartsoft/src/startstop-hooks.sh $TMPDIR/startstop-hooks-component-BT_runner.sh 2>/dev/null
#rsync -l -r -v --progress --exclude ".svn" $DEPLOY_COMPONENT_FILES_PATHS_BT_tickDispatcher $TMPDIR/BT_tickDispatcher_data/
if [ ! "$DEPLOY_COMPONENT_FILES_PATHS_BT_tickDispatcher" = "" ]; then
	cp -rv $DEPLOY_COMPONENT_FILES_PATHS_BT_tickDispatcher $TMPDIR/BT_tickDispatcher_data/ 2>&1
fi

cp -v $REFERENCED_PROJECT_BT_tickDispatcher/smartsoft/src/startstop-hooks.sh $TMPDIR/startstop-hooks-component-BT_tickDispatcher.sh 2>/dev/null
#rsync -l -r -v --progress --exclude ".svn" $DEPLOY_COMPONENT_FILES_PATHS_GraspingSkill $TMPDIR/GraspingSkill_data/
if [ ! "$DEPLOY_COMPONENT_FILES_PATHS_GraspingSkill" = "" ]; then
	cp -rv $DEPLOY_COMPONENT_FILES_PATHS_GraspingSkill $TMPDIR/GraspingSkill_data/ 2>&1
fi

cp -v $REFERENCED_PROJECT_GraspingSkill/smartsoft/src/startstop-hooks.sh $TMPDIR/startstop-hooks-component-GraspingSkill.sh 2>/dev/null
#rsync -l -r -v --progress --exclude ".svn" $DEPLOY_COMPONENT_FILES_PATHS_YarpNavigationClient $TMPDIR/Navigationskill_data/
if [ ! "$DEPLOY_COMPONENT_FILES_PATHS_YarpNavigationClient" = "" ]; then
	cp -rv $DEPLOY_COMPONENT_FILES_PATHS_YarpNavigationClient $TMPDIR/Navigationskill_data/ 2>&1
fi

cp -v $REFERENCED_PROJECT_YarpNavigationClient/smartsoft/src/startstop-hooks.sh $TMPDIR/startstop-hooks-component-Navigationskill.sh 2>/dev/null
#rsync -l -r -v --progress --exclude ".svn" $DEPLOY_COMPONENT_FILES_PATHS_VisionSkill $TMPDIR/VisionSkill_data/
if [ ! "$DEPLOY_COMPONENT_FILES_PATHS_VisionSkill" = "" ]; then
	cp -rv $DEPLOY_COMPONENT_FILES_PATHS_VisionSkill $TMPDIR/VisionSkill_data/ 2>&1
fi

cp -v $REFERENCED_PROJECT_VisionSkill/smartsoft/src/startstop-hooks.sh $TMPDIR/startstop-hooks-component-VisionSkill.sh 2>/dev/null
	# actually deploy:
	rsync -z -l -r -v --progress --exclude ".svn" -e ssh $TMPDIR/ $SSH_TARGET
fi


if [ "$?" != "0" ]; then
	echo "ERROR: Files could not be deployed to remote host."
	#gdialog --title ERROR --msgbox "Files could not be deployed host."
	exit 1
fi

echo -e "\n\nDeployment to device localhost finished.\n\n"
