//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _TEST_QUERYSERVER_HH
#define _TEST_QUERYSERVER_HH
	
#include <iostream>
#include "aceSmartSoft.hh"
#include "smartQueryServerTaskTrigger_T.h"
#include "Test_QueryServerCore.hh"
#include "Test_QueryServerImpl.hh"

// include communication objects
#include <CommBasicObjects/CommBaseState.hh>
#include <CommBasicObjects/CommBaseStateACE.hh>
#include <CommYARP_BT/CommTickCommand.hh>
#include <CommYARP_BT/CommTickCommandACE.hh>
#include <CommYARP_BT/CommTickResult.hh>
#include <CommYARP_BT/CommTickResultACE.hh>
#include <CommBasicObjects/CommVoid.hh>
#include <CommBasicObjects/CommVoidACE.hh>

// include tasks
// include UpcallManagers

// include input-handler
// include input-handler
#include "BaseStateQueryServiceAnswHandler.hh"
#include "BehaviourTreeTickQueryServiceAnswHandler.hh"


// include handler
#include "CompHandler.hh"


#include "SmartStateChangeHandler.hh"

#define COMP Test_QueryServer::instance()

class Test_QueryServer : public Test_QueryServerCore {
private:
	static Test_QueryServer _test_QueryServer;
	
	// constructor
	Test_QueryServer();
	
	// copy-constructor
	Test_QueryServer(const Test_QueryServer& cc);
	
	// destructor
	~Test_QueryServer() { };
	
	// load parameter from ini file
	void loadParameter(int argc, char* argv[]);
	
	// instantiate comp-handler
	CompHandler compHandler;
	
	Smart::TaskTriggerSubject* getInputTaskTriggerFromString(const std::string &client);
	
public:
	// component
	Test_QueryServerImpl *component;
	
	
	// define tasks
	
	// define input-ports
	
	// define request-ports
	
	// define input-handler
	
	// define output-ports
	
	// define answer-ports
	Smart::IQueryServerPattern<CommBasicObjects::CommVoid, CommBasicObjects::CommBaseState,SmartACE::QueryId> *baseState_Server;
	Smart::QueryServerTaskTrigger<CommBasicObjects::CommVoid, CommBasicObjects::CommBaseState,SmartACE::QueryId> *baseState_ServerInputTaskTrigger;
	Smart::IQueryServerPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult,SmartACE::QueryId> *tick_Server;
	Smart::QueryServerTaskTrigger<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult,SmartACE::QueryId> *tick_ServerInputTaskTrigger;
	
	// define request-handlers
	BaseStateQueryServiceAnswHandler *baseStateQueryServiceAnswHandler;
	BehaviourTreeTickQueryServiceAnswHandler *behaviourTreeTickQueryServiceAnswHandler;
	
	
	// define default slave ports
	SmartACE::StateSlave *stateSlave;
	SmartStateChangeHandler *stateChangeHandler;
	SmartACE::WiringSlave *wiringSlave;
	
	
	void init(int argc, char *argv[]);
	void run();
	
	void setStartupFinished();
	Smart::StatusCode connectAndStartAllServices();
	void startAllTasks();
	void startAllTimers();
	

	// return singleton instance
	static Test_QueryServer* instance()
	{
		return (Test_QueryServer*)&_test_QueryServer;
	}
	
	// connections parameter
	struct connections_struct
	{
		// component struct
		struct component_struct
		{
			// the name of the component
			std::string name;
			std::string initialComponentMode;
			std::string defaultScheduler;
			bool useLogger;
		} component;
		
		//--- task parameter ---
		
		//--- upcall parameter ---
		
		//--- server port parameter ---
		struct BaseState_Server_struct {
				std::string serviceName;
		} baseState_Server;
		struct Tick_Server_struct {
				std::string serviceName;
		} tick_Server;
	
		//--- client port parameter ---
		
	} connections;
};
#endif
