//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "BehaviourTreeTick_QueryServiceHandler.hh"
#include "BT_TickManager.hh"

BehaviourTreeTick_QueryServiceHandler::BehaviourTreeTick_QueryServiceHandler(Smart::IQueryServerPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult, SmartACE::QueryId>* server)
:	BehaviourTreeTick_QueryServiceHandlerCore(server)
{
	
}

BehaviourTreeTick_QueryServiceHandler::~BehaviourTreeTick_QueryServiceHandler()
{
	
}


void BehaviourTreeTick_QueryServiceHandler::handleQuery(const SmartACE::QueryId &id, const CommYARP_BT::CommTickCommand& request) 
{
	CommYARP_BT::CommTickResult answer;
	
	// implement your query handling logic here and fill in the answer object
	
	CommYARP_BT::TickCommand cmd = request.getCommand();
	CommYARP_BT::TickResult  res = CommYARP_BT::TickResult::Error;
	std::string tickParam = request.getParameter();

	std::cout << "Tick Manager Received tick request: " << tickParam << std::endl;

	//	sleep(4);

	std::string skill = tickParam;
	auto it = COMP->tickables_map.find(skill);
	if( it == COMP->tickables_map.end())
	{
		std::cout << "Error: skill " << skill << " not found!";
		res = CommYARP_BT::TickResult::Error;
	}
	else
	{
		res = (int) (*it).second.tickerInstance->tick(cmd /* (*it).second.command*/, (*it).second.params);
	}

	answer.setResult(res);
	std::cout << "answering query id " << id << "  with value: " << answer.getResult().to_string() << "  (res " << (int)res << " " << res << ")" << std::endl << std::endl;
	this->server->answer(id, answer);
}
