//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _BRIDGEV3_TOYARP_COMMNAVIGATIONVELOCITYCORE_HH
#define _BRIDGEV3_TOYARP_COMMNAVIGATIONVELOCITYCORE_HH
	
#include "aceSmartSoft.hh"
#include <iostream>

#include <yarp/os/Port.h>
#include <yarp/os/Bottle.h>
#include <yarp/os/Network.h>

class BridgeV3_ToYarp_CommNavigationVelocityCore
{
public:
	yarp::os::Network yarp;
	yarp::os::BufferedPort<yarp::os::Bottle> commandPort;

public:
	BridgeV3_ToYarp_CommNavigationVelocityCore();
	void onStartup();
};
	
#endif
