//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _NAVIGATIONVELOCITYSERVICEINHANDLER_HH
#define _NAVIGATIONVELOCITYSERVICEINHANDLER_HH

#include "NavigationVelocityServiceInHandlerCore.hh"
	
class NavigationVelocityServiceInHandler  : public NavigationVelocityServiceInHandlerCore
{		
public:
	NavigationVelocityServiceInHandler(Smart::InputSubject<CommBasicObjects::CommNavigationVelocity> *subject, const int &prescaleFactor=1);
	virtual ~NavigationVelocityServiceInHandler();
	
	virtual void on_NavigationVelocityServiceIn(const CommBasicObjects::CommNavigationVelocity &input);
};

#endif
