//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMYARP_BT_COMMTICKCOMMAND_H_
#define COMMYARP_BT_COMMTICKCOMMAND_H_

#include "CommYARP_BT/CommTickCommandCore.hh"

namespace CommYARP_BT {
		
class CommTickCommand : public CommTickCommandCore {
	public:
		// default constructors
		CommTickCommand();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommTickCommand(const CommYARP_BT::TickCommand &command, const std::string &parameter);
		
		CommTickCommand(const CommTickCommandCore &commTickCommand);
		CommTickCommand(const DATATYPE &commTickCommand);
		virtual ~CommTickCommand();
		
		// use framework specific getter and setter methods from core (base) class
		using CommTickCommandCore::get;
		using CommTickCommandCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommTickCommand &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommYARP_BT */
#endif /* COMMYARP_BT_COMMTICKCOMMAND_H_ */
