//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "PushTask.hh"
#include "PushServer.hh"

#include <iostream>

#include <yarp/os/Time.h>

PushTask::PushTask(SmartACE::SmartComponent *comp) 
:	PushTaskCore(comp)
{
	std::cout << "constructor PushTask\n";
}
PushTask::~PushTask() 
{
	std::cout << "destructor PushTask\n";
}

int PushTask::on_entry()
{
	// do initialization procedures here, which are called once, each time the task is started
	// it is possible to return != 0 (e.g. when initialization fails) then the task is not executed further
	return 0;
}

int PushTask::on_execute()
{
	// this method is called from an outside loop,
	// hence, NEVER use an infinite loop (like "while(1)") here inside!!!
	// also do not use blocking calls which do not result from smartsoft kernel
	
	// to get the incoming data, use this methods:
	Smart::StatusCode status;
	static int i=0;

	std::cout << "Hello from PushTask " << std::endl;

    yarp::os::Bottle bt;
    bt.addInt32(i);
    bt.addDouble(yarp::os::Time::now());
    COMP->yarpPushServer.put(bt);
    yarp::os::Time::delay(0.5);
    i++;

	// it is possible to return != 0 (e.g. when the task detects errors), then the outer loop breaks and the task stops
	return 0;
}
int PushTask::on_exit()
{
	// use this method to clean-up resources which are initialized in on_entry() and needs to be freed before the on_execute() can be called again
	return 0;
}
