//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _PUSHSERVERCORE_HH
#define _PUSHSERVERCORE_HH
	
#include "aceSmartSoft.hh"
#include <iostream>

#include <yarp/os/Network.h>						// Include YARP network core
#include <yarp/os/Bottle.h>							// Include communication data object from main YARP package
#include <yarp/smartsoft/PushPatternServer.h>		// Include RobMoSys compatible YARP port from interface library

class PushServerCore
{
private:
	yarp::os::Network yarp;

public:
	PushServerCore();

	yarp::smartsoft::PushPatternServer<yarp::os::Bottle> yarpPushServer;
};
	
#endif
