//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include <iostream>
#include "TestV3_StateSlave.hh"
	
	
TestV3_StateSlave TestV3_StateSlave::_testV3_StateSlave;
	
int main(int argc, char *argv[])
{
	std::cout << "main...\n";
	TestV3_StateSlave::instance()->init(argc, argv);
	TestV3_StateSlave::instance()->run();
	std::cout << "... main() end. return 0." << std::endl;
	return 0;
}
