//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _ACTIVITY5_HH
#define _ACTIVITY5_HH

#include "Activity5Core.hh"

class Activity5  : public Activity5Core
{
private:
public:
	Activity5(SmartACE::SmartComponent *comp);
	virtual ~Activity5();
	
	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
