//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "Activity5.hh"
#include "BridgeV3_ToYarp_CommNavigationVelocity.hh"

#include <iostream>

Activity5::Activity5(SmartACE::SmartComponent *comp) 
:	Activity5Core(comp)
{
	std::cout << "constructor Activity5\n";
}
Activity5::~Activity5() 
{
	std::cout << "destructor Activity5\n";
}



int Activity5::on_entry()
{
	// do initialization procedures here, which are called once, each time the task is started
	// it is possible to return != 0 (e.g. when initialization fails) then the task is not executed further
	COMP->is_newData = false;
	return 0;
}

int Activity5::on_execute()
{
	// this method is called from an outside loop,
	// hence, NEVER use an infinite loop (like "while(1)") here inside!!!
	// also do not use blocking calls which do not result from smartsoft kernel
	
	// to get the incoming data, use this methods:
	Smart::StatusCode status;
	std::cout << "Hello from Activity5 " << std::endl;

	if(COMP->is_newData)
	{
		COMP->input = COMP->newData;
		COMP->is_newData = false;

		yarp::os::Bottle & velCmd = COMP->commandPort.prepare();
		velCmd.clear();
		velCmd.addInt32(3);
		velCmd.addDouble(COMP->input.get_vX(1));
		velCmd.addDouble(COMP->input.get_vY(1));
		velCmd.addDouble(COMP->input.getOmega()*180/M_PI);
		velCmd.addInt32(100);
		COMP->commandPort.write();
		std::cout << "Sent cmd via yarp -> " << velCmd.toString() << std::endl;
	}
	else
		usleep(200 * 1000);

	// it is possible to return != 0 (e.g. when the task detects errors), then the outer loop breaks and the task stops
	return 0;
}

int Activity5::on_exit()
{
	// use this method to clean-up resources which are initialized in on_entry() and needs to be freed before the on_execute() can be called again
	return 0;
}
