//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _DUMMYTASK_HH
#define _DUMMYTASK_HH

#include "DummyTaskCore.hh"
#include <yarp/dev/IRangefinder2D.h>
#include <yarp/dev/IFrameTransform.h>
#include <yarp/dev/LaserMeasurementData.h>


class DummyTask  : public DummyTaskCore
{
private:
	yarp::dev::IFrameTransform *iFrame;
	yarp::dev::IRangefinder2D  *iLaser;
	std::string robotPose_tfName, laserPose_tfName, world_tfName;
	std::vector<yarp::dev::LaserMeasurementData> data;

	double	laserScan_distanceMin;
	double	laserScan_distanceMax;
	double	laserScan_angleMin;
	double	laserScan_angleMax;
	double  laserScan_step;

public:
	DummyTask(SmartACE::SmartComponent *comp);
	virtual ~DummyTask();

	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
