//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _YARPNAVIGATIONCLIENTCORE_HH
#define _YARPNAVIGATIONCLIENTCORE_HH
	
#include "aceSmartSoft.hh"
#include <iostream>

#include <yarp/os/Network.h>
#include <yarp/dev/PolyDriver.h>
#include <yarp/dev/INavigation2D.h>
#include <yarp/os/Port.h>
#include <atomic>

class YarpNavigationClientCore
{
private:

public:
	YarpNavigationClientCore();

	yarp::os::Network yarp;
	yarp::dev::PolyDriver     navClient;
	yarp::dev::INavigation2D *iNav;

	yarp::os::Port      pathPlanner_port;
	yarp::os::Port      goTo_port;

	std::atomic<bool>   initialized;
};
	
#endif
