//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _GRASPINGSKILLCORE_HH
#define _GRASPINGSKILLCORE_HH
	
#include "aceSmartSoft.hh"
#include <iostream>

#include <yarp/os/Network.h>
#include <yarp/dev/IEncoders.h>
#include <yarp/os/RpcClient.h>
#include <yarp/dev/PolyDriver.h>
#include <yarp/dev/IPositionControl.h>

class GraspingSkillCore
{
public:
	yarp::os::Network yarp;
	yarp::os::RpcClient RPChome;
	yarp::os::RpcClient RPCgrasp;
	yarp::os::Port  blackBoard_Client;

    GraspingSkillCore();
};
	
#endif
