//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _TICKHANDLER_USER_HH
#define _TICKHANDLER_USER_HH
		
#include "TickHandlerCore.hh"

class TickHandler : public TickHandlerCore
{
private:
	CommYARP_BT::TickResult handle_tick_goTo(const  std::vector<double> location);
	CommYARP_BT::TickResult handle_tick_check(const std::vector<double> location);
	std::vector<double> dummyPos_rightArm{45.0, 20.0, -40.0, 62.0, 5.0, 0.0, 0.0, 0.0};

public:
	TickHandler(Smart::IQueryServerPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult, SmartACE::QueryId>* server);
	virtual ~TickHandler();
	virtual void handleQuery(const SmartACE::QueryId &id, const CommYARP_BT::CommTickCommand& request);
};
#endif
