//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _BT_RUNNER_HH
#define _BT_RUNNER_HH
	
#include <iostream>
#include "aceSmartSoft.hh"
#include "smartQueryServerTaskTrigger_T.h"
#include "BT_runnerCore.hh"
#include "BT_runnerImpl.hh"

// include communication objects
#include <CommYARP_BT/CommTickCommand.hh>
#include <CommYARP_BT/CommTickCommandACE.hh>
#include <CommYARP_BT/CommTickResult.hh>
#include <CommYARP_BT/CommTickResultACE.hh>

// include tasks
#include "Task1.hh"
// include UpcallManagers

// include input-handler
// include input-handler


// include handler
#include "CompHandler.hh"


#include "SmartStateChangeHandler.hh"

#define COMP BT_runner::instance()

class BT_runner : public BT_runnerCore {
private:
	static BT_runner _bT_runner;
	
	// constructor
	BT_runner();
	
	// copy-constructor
	BT_runner(const BT_runner& cc);
	
	// destructor
	~BT_runner() { };
	
	// load parameter from ini file
	void loadParameter(int argc, char* argv[]);
	
	// instantiate comp-handler
	CompHandler compHandler;
	
	Smart::TaskTriggerSubject* getInputTaskTriggerFromString(const std::string &client);
	
public:
	// component
	BT_runnerImpl *component;
	
	
	// define tasks
	Smart::TaskTriggerSubject* task1Trigger;
	Task1 *task1;
	
	// define input-ports
	
	// define request-ports
	Smart::IQueryClientPattern<CommYARP_BT::CommTickCommand, CommYARP_BT::CommTickResult,SmartACE::QueryId> *behaviourTreeTickQueryServiceReq;
	
	// define input-handler
	
	// define output-ports
	
	// define answer-ports
	
	// define request-handlers
	
	
	// define default slave ports
	SmartACE::StateSlave *stateSlave;
	SmartStateChangeHandler *stateChangeHandler;
	SmartACE::WiringSlave *wiringSlave;
	
	
	void init(int argc, char *argv[]);
	void run();
	
	void setStartupFinished();
	Smart::StatusCode connectAndStartAllServices();
	void startAllTasks();
	void startAllTimers();
	
	Smart::StatusCode connectBehaviourTreeTickQueryServiceReq(const std::string &serverName, const std::string &serviceName);

	// return singleton instance
	static BT_runner* instance()
	{
		return (BT_runner*)&_bT_runner;
	}
	
	// connections parameter
	struct connections_struct
	{
		// component struct
		struct component_struct
		{
			// the name of the component
			std::string name;
			std::string initialComponentMode;
			std::string defaultScheduler;
			bool useLogger;
		} component;
		
		//--- task parameter ---
		struct Task1_struct {
			double minActFreq;
			double maxActFreq;
			std::string trigger;
			// only one of the following two params is 
			// actually used at run-time according 
			// to the system config model
			double periodicActFreq;
			// or
			std::string inPortRef;
			int prescale;
			// scheduling parameters
			std::string scheduler;
			int priority;
			int cpuAffinity;
		} task1;
		
		//--- upcall parameter ---
		
		//--- server port parameter ---
	
		//--- client port parameter ---
		struct BehaviourTreeTickQueryServiceReq_struct {
			bool initialConnect;
			std::string serverName;
			std::string serviceName;
			std::string wiringName;
			long interval;
		} behaviourTreeTickQueryServiceReq;
		
	} connections;
};
#endif
